name: Build EXE
on: [workflow_dispatch] # Allows you to run it manually

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x' # Or the version used by the project

      - name: Build Project
        run: dotnet build --configuration Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FluentFlyout-EXE
          path: '**/bin/Release/**/FluentFlyout.exe'
