name: Build EXE
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Updated for modern compatibility

      - name: Restore Dependencies
        run: msbuild FluentFlyout.sln /t:Restore /p:Configuration=Release

      - name: Build WPF Project Only
        # We target the WPF folder directly to avoid the MSIX error
        run: msbuild FluentFlyoutWPF\FluentFlyout.csproj /p:Configuration=Release /p:Platform=x64

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FluentFlyout-Standalone
          path: 'FluentFlyoutWPF\bin\x64\Release\net*-windows*\**\*'
